#!/bin/sh

echo "anki-audio-init: START" > /dev/kmsg

# wait for /sys/class/sound/card0 to appear
# indicating that the alsa driver has detected our sound system

MAX_RETRIES=120 # 60 sec
COUNT=0
while [ ! -e /sys/class/sound/card0 ]
do
  sleep 0.5
  COUNT=$((COUNT+1))
  if [ $COUNT -ge $MAX_RETRIES ]; then
    exit 1
  fi
done

if [ -f /data/vicw-volume ]; then
  VOLUME_SETTING=$(cat /data/vicw-volume | tr -d '\n\r' | tr '[:lower:]' '[:upper:]')
  case "$VOLUME_SETTING" in
    "MUTE")
      VOLUME_VALUE=0
      ;;
    "LOW")
      VOLUME_VALUE=50
      ;;
    "MEDIUM")
      VOLUME_VALUE=60
      ;;
    "MEDIUM HIGH")
      VOLUME_VALUE=65
      ;;
    "HIGH")
      VOLUME_VALUE=70
      ;;
    *)
      echo "anki-audio-init: Unknown volume setting '$VOLUME_SETTING', using default" > /dev/kmsg
      VOLUME_VALUE=$DEFAULT_VOLUME
      ;;
  esac
else
  echo "anki-audio-init: Volume file not found, using high volume and making file for next time." > /dev/kmsg
  echo HIGH > /data/vicw-volume
  VOLUME_VALUE=70
fi

echo "anki-audio-init: Setting volume to $VOLUME_VALUE ($VOLUME_SETTING)" > /dev/kmsg

# BRC/JMR: Use amixer controls to find "numid" params


# tinymix set "PRI_MI2S_RX Audio Mixer MultiMedia1" 1
amixer cset numid=1440 1


# tinymix set "RX3 MIX1 INP1" "RX1"
amixer cset numid=1633 "RX1"


# tinymix set "SPK" 1
amixer cset numid=1641 1

# tinymix set "RX3 Digital Volume" 74
amixer cset numid=33 74

[ ! -f /run/after_maintenance_reboot ] && sleep 3 && aplay /bin/tam-boot-chime.wav

# no longer sets it to 74, calls it from file
amixer cset numid=33 $VOLUME_VALUE


